//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Packet.Server.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Packet.Server.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /index.html
        ///.
        /// </summary>
        internal static string SampleHttpRequest_0_9_1 {
            get {
                return ResourceManager.GetString("SampleHttpRequest_0_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /index.html extra data
        ///.
        /// </summary>
        internal static string SampleHttpRequest_0_9_2 {
            get {
                return ResourceManager.GetString("SampleHttpRequest_0_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /index.html extra data
        ///extra
        ///data
        ///on
        ///multiple
        ///lines
        ///.
        /// </summary>
        internal static string SampleHttpRequest_0_9_3 {
            get {
                return ResourceManager.GetString("SampleHttpRequest_0_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /4848 HTTP/1.0
        ///Connection: Keep-Alive
        ///User-Agent: Mozilla/3.01 (X11; I; SunOS 5.4 sun4m)
        ///Pragma: no-cache
        ///Host: tecfa.unige.ch:7778
        ///Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*
        ///.
        /// </summary>
        internal static string SampleHttpRequest_1_0_1 {
            get {
                return ResourceManager.GetString("SampleHttpRequest_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAD /4848 HTTP/1.0
        ///Connection: Keep-Alive
        ///User-Agent: Mozilla/3.01 (X11; I; SunOS 5.4 sun4m)
        ///Pragma: no-cache
        ///Host: tecfa.unige.ch:7778
        ///Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*
        ///.
        /// </summary>
        internal static string SampleHttpRequest_1_0_2 {
            get {
                return ResourceManager.GetString("SampleHttpRequest_1_0_2", resourceCulture);
            }
        }
    }
}
